login_url = 'https://b2c.passport.rt.ru'
valid_email = 'dimarahmatullin95@gmail.com'
valid_password = '152152Qq'
valid_phone_number = '+79182154261'
valid_login = 'Ввести валидный логин' #дается только клиентам Ростелеком
valid_account_number = 'Ввести валидный номер лицевого счета' #дается только клиентам Ростелеком
invalid_email = 'testtest@alo.com'
invalid_password = 'Alo012'
invalid_phone_number = '+79819542813'
invalid_login = 'testtest@by.com'
invalid_account_number = 'gtjkl_12334345445'
empty_email = ''
empty_password = ''
empty_phone_number = ''
empty_login = ''
empty_account_number = ''
name = 'Дима'
surname = 'Рахматуллин'
new_email = 'test2@by.com'
lesser_password = 'qWe1rty'
bigger_password = 'QWEr1TYUIoPa2SDfGhjkL'
cyrillic_password = 'приветпривет'
no_caps_password = '1qwertyuio'
no_numbers_password = 'Qwertyuiopa'


